export const mockPatients = [
  {
    id: '1',
    nome: 'Maria Silva',
    email: 'maria@email.com',
    telefone: '(11) 99999-0001',
    ultimoHumor: {
      id: 'mood1',
      data: new Date().toISOString(),
      escala: 4,
      observacoes: 'Dia produtivo, me senti bem após a sessão',
      pacienteId: '1',
    },
    totalRegistros: 15,
    mediaHumor: 3.8,
    ultimaConsulta: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: '2',
    nome: 'João Santos',
    email: 'joao@email.com',
    telefone: '(11) 99999-0002',
    ultimoHumor: {
      id: 'mood2',
      data: new Date(Date.now() - 86400000).toISOString(),
      escala: 2,
      observacoes: 'Dia difícil no trabalho, me senti sobrecarregado',
      pacienteId: '2',
    },
    totalRegistros: 8,
    mediaHumor: 2.5,
    ultimaConsulta: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: '3',
    nome: 'Ana Costa',
    email: 'ana@email.com',
    telefone: '(11) 99999-0003',
    ultimoHumor: {
      id: 'mood3',
      data: new Date(Date.now() - 86400000 * 3).toISOString(),
      escala: 5,
      observacoes: 'Excelente dia! Consegui aplicar as técnicas que aprendemos',
      pacienteId: '3',
    },
    totalRegistros: 22,
    mediaHumor: 4.2,
    ultimaConsulta: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: '4',
    nome: 'Carlos Oliveira',
    email: 'carlos@email.com',
    telefone: '(11) 99999-0004',
    totalRegistros: 5,
    mediaHumor: 3.2,
    ultimaConsulta: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: '5',
    nome: 'Lucia Ferreira',
    email: 'lucia@email.com',
    telefone: '(11) 99999-0005',
    ultimoHumor: {
      id: 'mood5',
      data: new Date(Date.now() - 86400000 * 2).toISOString(),
      escala: 3,
      observacoes: 'Dia normal, sem grandes alterações no humor',
      pacienteId: '5',
    },
    totalRegistros: 12,
    mediaHumor: 3.5,
    ultimaConsulta: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
];
